import 'bootstrap/dist/css/bootstrap.min.css';
import '@fortawesome/fontawesome-free/css/all.min.css';

import "./globals.css";
import { Inter } from "next/font/google";
import Link from 'next/link';
import Navbar from './Navbar/Navbar';
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
<Navbar/>
        
        {children}
        <footer id='footer'>
        <div class="container py-5">
<div class="row justify-content-center">
  <div class="col-md-4 col-12" data-aos="fade-up" data-aos-duration="3000">
    <h4 class="text-white py-2">
      Customer Service
    </h4>
    <ul class="p-0 fs-6">
      <li class="py-2 d-flex flex-column">
        <span>UAE office 🇦🇪
        </span>
        <Link href="#">
          +971 4 323 4578
        </Link>

      </li>
      <li class="py-2 d-flex flex-column">
        <span>UAE office 🇦🇪
        </span>
        <Link href="#">
          +971 4 323 4578
        </Link>

      </li>
      <li class="py-2 d-flex flex-column">
        <span>E-mail 📨

        </span>
        <Link href="#">
          support@ratecards.co

        </Link>

      </li>
    </ul>
  </div>
  <div class="col-md-4 col-12" data-aos="fade-up" data-aos-duration="3000">
    <h4 class="text-white py-2">
      Quick Links
    </h4>
    <ul class="p-0 fs-6">
      <li class="py-1">
        <Link href="trackMyorder.html">
          Track my Order
        </Link>
      </li>
      <li class="py-1">
        <Link href="contacus.html">
          Contact
        </Link>
      </li>
      <li class="py-1">
        <Link href="FAQ.html">
          FAQ
        </Link>
      </li>
      <li class="py-1">
        <Link href="privacy.html">
          Privacy Policy
        </Link>
      </li>
      <li class="py-1">
        <Link href="Refundpolicy.html">
          Refund Policy
        </Link>
      </li>
      <li class="py-1">
        <Link href="terms.html">
          Terms of Service
        </Link>

      </li>
      <li class="py-1">
        <Link href="shappingPolicy.html">
          Shipping Policy
        </Link>
      </li>
    </ul>
  </div>
  <div class="col-md-4 col-12" data-aos="fade-up" data-aos-duration="3000">
    <img width="230" src="https://ratecards.co/cdn/shop/files/Asset_6white.png?v=1689374514&width=210" />

  </div>
</div>
<div class="row justify-content-center py-5">

  <ul class="social d-flex justify-content-center">
    <li>
      <Link href="#">
        <i class="fab fa-facebook-f icon"></i>
      </Link>
    </li>
    <li>
      <Link href="#"><i class="fab fa-twitter icon"></i></Link>
    </li>
    <li>
      <Link href="#"><i class="fab fa-linkedin-in icon"></i></Link>
    </li>
    <li>
      <Link href="#"><i class="fab fa-google-plus-g icon"></i></Link>
    </li>
  </ul>

</div>
<div class="row py-5  border-top border-1 border-dark justify-content-center">
<div class="col-lg-5 col-12 d-flex  justify-content-lg-start justify-content-center align-items-center" data-aos="fade-right"
data-aos-duration="1000">

<div class="dropup-center py-lg-0 py-3 dropup">
  <h6 class="mb-3 text-white text-center">
    Country/region
  </h6>
  <button class="btn border border-1 text-white dropdown-toggle" type="button" data-bs-toggle="dropdown"
    aria-expanded="false">
    AED د.إ | Egypt
  </button>
  <ul class="dropdown-menu bg-black ">
    <li><Link class="dropdown-item text-white" href="#"> د.إ |
        Afghanistan</Link></li>
    <li><Link class="dropdown-item text-white" href="#">AED د.إ | Egypt</Link></li>
    <li><Link class="dropdown-item text-white" href="#"> د.إ |
        Ascension Island</Link></li>
  </ul>



</div>


</div>
  <div class="col-lg-5 col-12 d-flex justify-content-lg-end justify-content-center align-items-center"
    data-aos="fade-right" data-aos-duration="1000">

  </div>



</div>
<div class="row">
  <div class="col-12 text-center fs-6 text-white">
    Powared by<span class="emcan"> <Link class="text-white" href="https://emcan-group.com/en">emcan</Link> </span>
  </div>

</div>

</div>
        </footer>

        </body>
    </html>
  );
}
